# Generated by Django 5.1.3 on 2024-12-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ne', models.CharField(max_length=10, unique=True, verbose_name='Базовая станция')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='Адрес')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('gsm', models.BooleanField(default=False)),
                ('umts', models.BooleanField(default=False)),
                ('lte', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Базовая станция',
                'verbose_name_plural': 'Базовые станции',
            },
        ),
    ]
